/* Takbai Internal Supervision - Admin User/Data Control */
(function(){
  'use strict';
  const q=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random().toString(36).slice(2);
  const val=id=>(document.getElementById(id)?.value??'').trim();
  const notify=(m,t='success')=>typeof showToast==='function'?showToast(m,t):alert(m);
  const auth=()=>typeof currentUser!=='undefined'&&currentUser?.authToken?currentUser.authToken:'';

  function adminGet(action,data={}){
    return new Promise((resolve,reject)=>{
      if(!auth())return reject(new Error('เซสชันผู้ดูแลหมดอายุ กรุณาเข้าสู่ระบบใหม่'));
      const cb='nited_admin_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');
      let timer;const clean=()=>{clearTimeout(timer);delete window[cb];s.remove();};
      window[cb]=r=>{clean();resolve(r||{});};s.onerror=()=>{clean();reject(new Error('เชื่อมต่อฐานข้อมูลไม่สำเร็จ'));};
      timer=setTimeout(()=>{clean();reject(new Error('หมดเวลารอฐานข้อมูล'));},20000);
      const p=Object.assign({action,authToken:auth()},data,{callback:cb});
      s.src=CONFIG.SCRIPT_URL+'?'+new URLSearchParams(p).toString();document.head.appendChild(s);
    });
  }
  async function adminPost(action,data={}){
    if(!auth())return{success:false,error:'เซสชันผู้ดูแลหมดอายุ กรุณาเข้าสู่ระบบใหม่'};
    if(typeof postViaForm!=='function')return{success:false,error:'ไม่พบตัวเชื่อมต่อฐานข้อมูล'};
    return postViaForm(Object.assign({action,authToken:auth()},data));
  }

  const schemas={
    bookings:{title:'การจอง',load:'getBookings',add:'addBooking',update:'updateBooking',del:'deleteBooking',fields:[['date','วันที่','date'],['time','เวลา','time'],['teacherName','ชื่อครู','text'],['department','กลุ่มสาระ','text'],['period','คาบ','text'],['subjectName','วิชา','text'],['subjectCode','รหัสวิชา','text'],['classLevel','ระดับชั้น','text'],['room','ห้อง','text'],['status','สถานะ','text']]},
    files:{title:'ไฟล์งาน',load:'getFiles',add:'addFile',update:'updateFile',del:'deleteFile',fields:[['teacherName','ชื่อครู','text'],['fileType','ประเภทไฟล์','text'],['fileName','ชื่อไฟล์','text'],['fileUrl','ลิงก์ไฟล์','url'],['driveFileId','Drive File ID','text'],['status','สถานะ','text']]},
    evaluations:{title:'ผลการประเมิน',load:'getEvaluations',add:'addEvaluation',update:'updateEvaluation',del:'deleteEvaluation',fields:[['teacherName','ชื่อครู','text'],['supervisionDate','วันที่นิเทศ','date'],['strengths','จุดเด่น','textarea'],['improvements','สิ่งที่ควรพัฒนา','textarea'],['suggestions','ข้อเสนอแนะ','textarea'],['summary','สรุปผล','textarea']]},
    users:{title:'ผู้ใช้งาน',load:'getUsers',add:'addUser',update:'updateUser',del:'deleteUser',fields:[['username','ชื่อผู้ใช้','text'],['password','รหัสผ่าน','password'],['role','สิทธิ์','role'],['fullName','ชื่อ-นามสกุล','text'],['department','กลุ่มสาระ/หน่วยงาน','text'],['active','สถานะบัญชี','active']]}
  };
  let data={bookings:[],files:[],evaluations:[],users:[]},currentTab='users';

  function isAdmin(){return typeof isAdmin!=='undefined'?Boolean(window.isAdmin):Boolean(document.querySelector('#navAdmin')?.offsetParent);}
  async function loadAll(){try{const keys=Object.keys(schemas);const out=await Promise.all(keys.map(async k=>{try{const r=await adminGet(schemas[k].load);return[k,r?.success?(r.data||[]):[]];}catch(e){return[k,[]];}}));out.forEach(([k,v])=>data[k]=v);render();}catch(e){notify(e.message,'error');}}
  function render(){const host=q('#adminControlCenter');if(!host)return;const s=schemas[currentTab],rows=data[currentTab]||[];
    host.innerHTML=`<div class="admin-cc-head"><div><div class="admin-cc-kicker"><i class="fas fa-shield-halved"></i> ADMIN CONTROL CENTER</div><h2>ศูนย์จัดการข้อมูล</h2><p>ข้อมูลทั้งหมดเชื่อมตรงกับ Google Sheets และบันทึกกลับฐานข้อมูลทันที</p></div><div class="admin-cc-head-actions"><span class="admin-cc-db"><i class="fas fa-database"></i> Google Sheets</span><button id="accRefresh" class="admin-cc-refresh"><i class="fas fa-rotate"></i> รีเฟรช</button></div></div>
    <div class="admin-cc-stats">${Object.entries(schemas).map(([k,x])=>`<button class="acc-stat ${k===currentTab?'active':''}" data-acc-tab="${k}"><span>${esc(x.title)}</span><strong>${data[k].length}</strong></button>`).join('')}</div>
    <div class="admin-cc-toolbar"><div><h3>${esc(s.title)}</h3><small>ข้อมูล ${rows.length} รายการ</small></div><div class="admin-cc-actions"><input id="accSearch" class="acc-search" placeholder="ค้นหาข้อมูล..." aria-label="ค้นหาข้อมูล"><button id="accAdd" class="btn btn-primary"><i class="fas fa-plus"></i> เพิ่ม${esc(s.title)}</button></div></div>
    <div class="admin-cc-table-wrap"><table class="admin-cc-table"><thead><tr>${s.fields.map(f=>`<th>${esc(f[1])}</th>`).join('')}<th>จัดการ</th></tr></thead><tbody id="accBody"></tbody></table></div>`;
    host.querySelectorAll('[data-acc-tab]').forEach(b=>b.onclick=()=>{currentTab=b.dataset.accTab;render();});q('#accRefresh').onclick=loadAll;q('#accAdd').onclick=()=>openEditor(null);q('#accSearch').oninput=e=>renderRows(e.target.value);renderRows('');
  }
  function display(v,type){if(type==='active')return String(v).toLowerCase()==='false'?'<span class="acc-badge off">ปิดใช้งาน</span>':'<span class="acc-badge on">ใช้งาน</span>';if(type==='role')return String(v)==='admin'?'<span class="acc-badge admin">ผู้ดูแลระบบ</span>':'<span class="acc-badge user">ผู้ใช้</span>';if(type==='password')return '<span class="acc-secret">••••••••</span>';if(type==='url'&&v)return`<a class="acc-link" href="${esc(v)}" target="_blank" rel="noopener"><i class="fas fa-external-link-alt"></i> เปิด</a>`;const t=String(v??'');return esc(t.length>80?t.slice(0,80)+'…':t)||'<span class="acc-empty">—</span>';}
  function renderRows(filter){const s=schemas[currentTab],body=q('#accBody');if(!body)return;const n=String(filter||'').toLowerCase(),rows=(data[currentTab]||[]).filter(r=>!n||s.fields.some(f=>String(r[f[0]]??'').toLowerCase().includes(n)));body.innerHTML=rows.length?rows.map(r=>`<tr>${s.fields.map(f=>`<td>${display(r[f[0]],f[2])}</td>`).join('')}<td class="acc-actions"><button class="acc-edit" data-id="${esc(r.id)}" title="แก้ไข"><i class="fas fa-pen"></i></button><button class="acc-delete" data-id="${esc(r.id)}" title="ลบ"><i class="fas fa-trash"></i></button></td></tr>`).join(''):`<tr><td colspan="${s.fields.length+1}" class="acc-no-data"><i class="fas fa-inbox"></i><div>ไม่พบข้อมูล</div></td></tr>`;body.querySelectorAll('.acc-edit').forEach(b=>b.onclick=()=>openEditor(rows.find(x=>String(x.id)===String(b.dataset.id))));body.querySelectorAll('.acc-delete').forEach(b=>b.onclick=()=>removeRow(b.dataset.id));}
  function openEditor(row){const s=schemas[currentTab],edit=Boolean(row);let html=s.fields.map(f=>{const id='acc_'+f[0],v=row?.[f[0]]??(f[0]==='active'?true:'');if(f[2]==='textarea')return`<div class="form-group acc-field"><label>${esc(f[1])}</label><textarea id="${id}" rows="3">${esc(v)}</textarea></div>`;if(f[2]==='role')return`<div class="form-group acc-field"><label>${esc(f[1])}</label><select id="${id}"><option value="user" ${v==='user'?'selected':''}>ผู้ใช้</option><option value="admin" ${v==='admin'?'selected':''}>ผู้ดูแลระบบ</option></select></div>`;if(f[2]==='active')return`<div class="form-group acc-field"><label>${esc(f[1])}</label><select id="${id}"><option value="true" ${String(v)!=='false'?'selected':''}>ใช้งาน</option><option value="false" ${String(v)==='false'?'selected':''}>ปิดใช้งาน</option></select></div>`;if(f[2]==='password')return`<div class="form-group acc-field"><label>${esc(f[1])}${edit?' <small>(เว้นว่าง = ใช้รหัสเดิม)</small>':''}</label><div class="acc-password"><input id="${id}" type="password" value="${edit?'':esc(v)}" autocomplete="new-password"><button type="button" id="accShowPw"><i class="fas fa-eye"></i></button></div></div>`;return`<div class="form-group acc-field"><label>${esc(f[1])}</label><input id="${id}" type="${f[2]}" value="${esc(v)}"></div>`;}).join('');
    let modal=q('#accModal');if(!modal){modal=document.createElement('div');modal.id='accModal';modal.className='acc-modal';document.body.appendChild(modal);}modal.innerHTML=`<div class="acc-modal-backdrop"></div><div class="acc-modal-card"><div class="acc-modal-head"><div><span>จัดการข้อมูล</span><h3>${edit?'แก้ไขผู้ใช้/ข้อมูล':'เพิ่มข้อมูลใหม่'}</h3></div><button id="accClose" class="acc-close"><i class="fas fa-xmark"></i></button></div><form id="accForm"><div class="acc-form-grid">${html}</div><div class="acc-modal-foot"><button type="button" id="accCancel" class="btn btn-light">ยกเลิก</button><button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> บันทึกลง Google Sheets</button></div></form></div>`;modal.classList.add('show');
    const close=()=>modal.classList.remove('show');q('#accClose').onclick=close;q('#accCancel').onclick=close;q('.acc-modal-backdrop').onclick=close;q('#accShowPw')?.addEventListener('click',()=>{const p=q('#acc_password');p.type=p.type==='password'?'text':'password';});
    q('#accForm').onsubmit=async e=>{e.preventDefault();const payload={id:row?.id||uid()};s.fields.forEach(f=>{let x=val('acc_'+f[0]);if(f[2]==='active')x=x==='true';if(f[2]==='password'&&edit&&x==='')return;payload[f[0]]=x;});if(currentTab==='users'){if(!payload.username)return notify('กรุณาระบุชื่อผู้ใช้','error');if(!edit&&!payload.password)return notify('กรุณาระบุรหัสผ่าน','error');if(!payload.fullName)return notify('กรุณาระบุชื่อ-นามสกุล','error');}
      const before=JSON.stringify(data[currentTab]);const r=await adminPost(edit?s.update:s.add,payload);if(r&&r.success===false)return notify(r.error||'บันทึกไม่สำเร็จ','error');close();notify('กำลังบันทึกข้อมูล...','info');setTimeout(async()=>{await loadAll();const found=(data[currentTab]||[]).find(x=>String(x.id)===String(payload.id)||String(x.username||'')===String(payload.username||''));if(edit&&!found)notify('ไม่พบข้อมูลหลังบันทึก กรุณาตรวจสอบ Google Sheets','error');else notify(edit?'แก้ไขข้อมูลสำเร็จ':'เพิ่มข้อมูลสำเร็จ');},900);};
  }
  async function removeRow(id){const row=(data[currentTab]||[]).find(x=>String(x.id)===String(id));if(!confirm(`ยืนยันลบ ${currentTab==='users'?(row?.username||'ผู้ใช้นี้'):'รายการนี้'} ?\nข้อมูลจะถูกลบจาก Google Sheets`))return;const r=await adminPost(schemas[currentTab].del,{id});if(r&&r.success===false)return notify(r.error||'ลบข้อมูลไม่สำเร็จ','error');notify('กำลังลบข้อมูล...','info');setTimeout(async()=>{await loadAll();if((data[currentTab]||[]).some(x=>String(x.id)===String(id)))notify('ลบไม่สำเร็จ กรุณาตรวจสอบสิทธิ์/Google Sheets','error');else notify('ลบข้อมูลสำเร็จ');},900);}
  function boot(){if(typeof window.isAdmin==='boolean'&&!window.isAdmin)return;const page=q('#page-admin');if(!page)return;let host=q('#adminControlCenter');if(!host){host=document.createElement('div');host.id='adminControlCenter';page.insertBefore(host,page.firstElementChild);}loadAll();}
  window.loadAdminControl=loadAll;window.addEventListener('load',()=>setTimeout(boot,700));
})();
