/* Takbai Internal Supervision - GitHub Pages client */
const CONFIG={SCRIPT_URL:'https://script.google.com/macros/s/AKfycbzAb8Ye8-l0DFVJZSazCZcaX6SYbU_s9HObOqiL2INsdA2tbp3YFY_xqonLJjeQE3Zjow/exec',SPREADSHEET_ID:'1e5530q7hRUdR6pNIx6tAv4JjNKadFibg7GE5ohuq4xU',DRIVE_FOLDER_ID:'1wVAG7EETgBcv5ftOFLLzdX-wbDEK95Dw'};
let currentUser=null,isAdmin=false,allBookings=[],allFiles=[],allEvaluations=[],allUsers=[],calendarInstances={};
const apiCall=(action,data={})=>jsonp(Object.assign({action},data));
function jsonp(params,timeout=20000){return new Promise((resolve,reject)=>{const cb='nited_cb_'+Date.now()+'_'+Math.random().toString(36).slice(2);const s=document.createElement('script');let timer;const cleanup=()=>{clearTimeout(timer);delete window[cb];s.remove();};window[cb]=x=>{cleanup();resolve(x||{});};s.onerror=()=>{cleanup();reject(new Error('เชื่อมต่อ Google Apps Script ไม่สำเร็จ'));};timer=setTimeout(()=>{cleanup();reject(new Error('หมดเวลารอเซิร์ฟเวอร์'));},timeout);s.src=CONFIG.SCRIPT_URL+(CONFIG.SCRIPT_URL.includes('?')?'&':'?')+new URLSearchParams(Object.assign({},params,{callback:cb})).toString();document.head.appendChild(s);});}
async function apiPost(action,data={}){try{return await postViaForm(Object.assign({action},data));}catch(e){return {success:false,error:e.message};}}
function postViaForm(payload){return new Promise((resolve,reject)=>{const iframe=document.createElement('iframe');iframe.name='nited_post_'+Date.now();iframe.style.display='none';document.body.appendChild(iframe);const form=document.createElement('form');form.method='POST';form.action=CONFIG.SCRIPT_URL;form.target=iframe.name;form.style.display='none';Object.keys(payload).forEach(k=>{const input=document.createElement('input');input.name=k;input.value=typeof payload[k]==='object'?JSON.stringify(payload[k]):String(payload[k]);form.appendChild(input);});document.body.appendChild(form);let done=false;const finish=(r,e)=>{if(done)return;done=true;setTimeout(()=>{form.remove();iframe.remove();},100);e?reject(e):resolve(r);};iframe.onload=()=>finish({success:true});iframe.onerror=()=>finish(null,new Error('ส่งข้อมูลไปเซิร์ฟเวอร์ไม่สำเร็จ'));form.submit();setTimeout(()=>{if(!done)finish({success:true});},12000);});}
function getLocalData(k){try{return JSON.parse(localStorage.getItem('nited2_'+k)||'[]');}catch(_){return[];}}function setLocalData(k,v){localStorage.setItem('nited2_'+k,JSON.stringify(v));}
function showToast(message,type='success'){const t=document.getElementById('toast');if(!t)return;t.textContent=message;t.className='toast toast-'+type+' show';setTimeout(()=>t.classList.remove('show'),3000);}
function showLoginError(m){const e=document.getElementById('loginError');e.textContent=m;e.style.display='block';}
function sha256(s){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)).then(b=>Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join(''));}
document.addEventListener('DOMContentLoaded',()=>{initLogin();initNavigation();initSidebarToggle();initBookingForm();initFileForm();initEvaluationForm();initAdminTabs();initUploadArea();initReportButtons();setTodayDate();});
function initLogin(){const f=document.getElementById('loginForm');if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const u=document.getElementById('loginUsername').value.trim(),p=document.getElementById('loginPassword').value.trim(),b=f.querySelector('button[type=submit]');b.disabled=true;b.innerHTML='<i class="fas fa-spinner fa-spin"></i> กำลังเข้าสู่ระบบ...';try{const r=await apiCall('login',{username:u,password:p});if(r.success&&r.user){currentUser=r.user;isAdmin=r.user.role==='admin';document.getElementById('loginError').style.display='none';showMainApp();}else showLoginError(r.message||r.error||'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง');}catch(err){showLoginError('เชื่อมต่อเซิร์ฟเวอร์ไม่สำเร็จ: '+err.message);}finally{b.disabled=false;b.innerHTML='<i class="fas fa-sign-in-alt"></i> เข้าสู่ระบบ';}});document.getElementById('logoutBtn')?.addEventListener('click',()=>{currentUser=null;isAdmin=false;document.getElementById('mainApp').style.display='none';document.getElementById('loginScreen').style.display='flex';f.reset();});}
async function showMainApp(){document.getElementById('loginScreen').style.display='none';document.getElementById('mainApp').style.display='flex';document.getElementById('currentUserName').textContent=currentUser.fullName||currentUser.username;if(isAdmin)document.getElementById('navAdmin').style.display='block';await loadAllData();initCalendars();}
function initNavigation(){document.querySelectorAll('.nav-item').forEach(i=>i.addEventListener('click',e=>{e.preventDefault();navigateTo(i.dataset.page);}));}
function navigateTo(page){document.querySelectorAll('.nav-item').forEach(i=>i.classList.toggle('active',i.dataset.page===page));document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById('page-'+page)?.classList.add('active');document.getElementById('pageTitle').textContent=({dashboard:'แดชบอร์ด',booking:'จองวันนิเทศ',files:'ส่งงาน/ไฟล์',evaluation:'ประเมินผลการนิเทศ',admin:'ผู้ดูแลระบบ'})[page]||page;if(page==='dashboard')loadDashboard();if(page==='admin')loadAdminData();if(page==='booking')loadMyBookings();if(page==='files')loadMyFiles();if(page==='evaluation')loadEvaluationData();document.getElementById('sidebar').classList.remove('open');}
function initSidebarToggle(){document.getElementById('sidebarToggle')?.addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));}
function setTodayDate(){const e=document.getElementById('todayDate');if(e)e.textContent=new Date().toLocaleDateString('th-TH',{year:'numeric',month:'long',day:'numeric',weekday:'long'});}
async function loadAllData(){const rs=await Promise.allSettled([apiCall('getBookings'),apiCall('getFiles'),apiCall('getEvaluations'),apiCall('getUsers')]);allBookings=rs[0].value?.data||[];allFiles=rs[1].value?.data||[];allEvaluations=rs[2].value?.data||[];allUsers=rs[3].value?.data||[];setLocalData('bookings',allBookings);setLocalData('files',allFiles);setLocalData('evaluations',allEvaluations);setLocalData('users',allUsers);loadDashboard();}
function loadDashboard(){const b=allBookings,f=allFiles;document.getElementById('statTotalBookings').textContent=b.length;document.getElementById('statCompleted').textContent=b.filter(x=>x.status==='นิเทศแล้ว').length;document.getElementById('statPending').textContent=b.filter(x=>x.status==='รอดำเนินการ').length;document.getElementById('statFiles').textContent=f.length;loadLatestBookings();loadLatestFiles();loadDeptChart();loadDashboardCalendar();}
function loadLatestBookings(){const e=document.getElementById('latestBookings');if(!e)return;const a=allBookings.slice(-5).reverse();e.innerHTML=a.length?a.map(b=>`<tr><td>${formatDate(b.date)}</td><td>${esc(b.teacherName)}</td><td>${esc(b.department)}</td><td>${getStatusBadge(b.status)}</td></tr>`).join(''):'<tr><td colspan="4">ยังไม่มีข้อมูล</td></tr>';}
function loadLatestFiles(){const e=document.getElementById('latestFiles');if(!e)return;const a=allFiles.slice(-5).reverse();e.innerHTML=a.length?a.map(f=>`<tr><td>${formatDate(f.timestamp)}</td><td>${esc(f.teacherName)}</td><td>${esc(f.fileType)}</td><td>${getStatusBadge(f.status)}</td></tr>`).join(''):'<tr><td colspan="4">ยังไม่มีข้อมูล</td></tr>';}
function loadDeptChart(){const c=document.getElementById('deptChart');if(!c||!window.Chart)return;if(calendarInstances.deptChart)calendarInstances.deptChart.destroy();const m={};allBookings.forEach(x=>m[x.department||'ไม่ระบุ']=(m[x.department||'ไม่ระบุ']||0)+1);calendarInstances.deptChart=new Chart(c,{type:'bar',data:{labels:Object.keys(m),datasets:[{label:'จำนวนการจอง',data:Object.values(m)}]},options:{responsive:true,plugins:{legend:{display:false}}}});}
function loadDashboardCalendar(){const c=document.getElementById('dashboardCalendar');if(!c||!window.FullCalendar)return;if(calendarInstances.dashboard)calendarInstances.dashboard.destroy();calendarInstances.dashboard=new FullCalendar.Calendar(c,{initialView:'dayGridMonth',locale:'th',height:'auto',events:allBookings.map(b=>({title:(b.teacherName||'')+' - '+(b.department||''),date:b.date}))});calendarInstances.dashboard.render();}
function initBookingForm(){const f=document.getElementById('bookingForm');if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const b={date:v('bookDate'),time:v('bookTime'),teacherName:v('bookTeacher'),department:v('bookDepartment'),period:v('bookPeriod'),subjectName:v('bookSubject'),subjectCode:v('bookSubjectCode'),classLevel:v('bookClassLevel'),room:v('bookRoom'),status:'รอดำเนินการ',timestamp:new Date().toISOString(),id:crypto.randomUUID?crypto.randomUUID():String(Date.now())};const conflict=allBookings.some(x=>x.date===b.date&&x.time===b.time&&x.room===b.room&&x.status!=='ปฏิเสธ');if(conflict)return showToast('วัน เวลา และห้องนี้ถูกจองแล้ว','error');const r=await apiPost('addBooking',b);if(!r.success)return showToast(r.error||'บันทึกการจองไม่สำเร็จ','error');allBookings.push(b);setLocalData('bookings',allBookings);f.reset();showToast('บันทึกการจองสำเร็จ');loadMyBookings();loadDashboard();refreshCalendars();});}
function loadMyBookings(){const e=document.getElementById('myBookings');if(!e)return;e.innerHTML=allBookings.slice().reverse().map(b=>`<tr><td>${formatDate(b.date)}</td><td>${esc(b.time)}</td><td>${esc(b.department)}</td><td>${esc(b.subjectName)}</td><td>${esc(b.classLevel)}</td><td>${esc(b.room)}</td><td>${getStatusBadge(b.status)}</td><td>${b.status==='รอดำเนินการ'?`<button class="btn btn-danger btn-sm" onclick="cancelBooking('${b.id}')"><i class="fas fa-times"></i></button>`:''}</td></tr>`).join('')||'<tr><td colspan="8">ยังไม่มีรายการจอง</td></tr>';}
async function cancelBooking(id){if(!confirm('ต้องการยกเลิกการจองนี้ใช่หรือไม่?'))return;const r=await apiPost('deleteBooking',{id});if(!r.success)return showToast(r.error||'ยกเลิกไม่สำเร็จ','error');allBookings=allBookings.filter(x=>x.id!==id);setLocalData('bookings',allBookings);showToast('ยกเลิกการจองแล้ว');loadMyBookings();loadDashboard();refreshCalendars();}
function initFileForm(){const f=document.getElementById('fileForm');if(!f)return;document.getElementById('fileType')?.addEventListener('change',()=>{const video=v('fileType')==='คลิปวิดีโอ';document.getElementById('fileUploadSection').style.display=video?'none':'block';document.getElementById('fileLinkSection').style.display=video?'block':'none';});f.addEventListener('submit',async e=>{e.preventDefault();const type=v('fileType');let d={teacherName:v('fileTeacher'),fileType:type,status:'รอตรวจสอบ',timestamp:new Date().toISOString(),id:crypto.randomUUID?crypto.randomUUID():String(Date.now())};if(type==='คลิปวิดีโอ'){d.fileUrl=v('fileLink');}else{const file=document.getElementById('fileInput')?.files[0];if(!file)return showToast('กรุณาเลือกไฟล์','error');if(file.size>10*1024*1024)return showToast('ไฟล์มีขนาดใหญ่เกิน 10MB','error');showToast('กำลังอัปโหลดไฟล์...','info');d.fileName=file.name;d.fileData=await readFileAsBase64(file);d.mimeType=file.type||'application/octet-stream';const u=await apiPost('uploadFileToDrive',d);if(!u.success)return showToast('อัปโหลดไม่สำเร็จ: '+(u.error||''),'error');d.driveFileId=u.fileId;d.fileUrl=u.fileUrl;delete d.fileData;delete d.mimeType;}const r=await apiPost('addFile',d);if(!r.success)return showToast(r.error||'บันทึกไฟล์ไม่สำเร็จ','error');allFiles.push(d);setLocalData('files',allFiles);f.reset();showToast('ส่งงานสำเร็จ');loadMyFiles();loadDashboard();});}
function readFileAsBase64(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(f);});}
function initUploadArea(){const a=document.getElementById('uploadArea'),i=document.getElementById('fileInput');if(!a||!i)return;a.onclick=()=>i.click();i.onchange=()=>{if(i.files[0])handleFileSelect(i.files[0]);};document.getElementById('removeFile')?.addEventListener('click',()=>{i.value='';document.getElementById('filePreview').style.display='none';a.style.display='block';});}
function handleFileSelect(f){if(f.size>10*1024*1024)return showToast('ไฟล์มีขนาดใหญ่เกิน 10MB','error');document.getElementById('fileName').textContent=`${f.name} (${(f.size/1024).toFixed(1)} KB)`;document.getElementById('filePreview').style.display='flex';document.getElementById('uploadArea').style.display='none';}
function loadMyFiles(){const e=document.getElementById('myFiles');if(!e)return;e.innerHTML=allFiles.slice(-10).reverse().map(f=>`<tr><td>${formatDate(f.timestamp)}</td><td>${esc(f.teacherName)}</td><td>${esc(f.fileType)}</td><td>${renderFileCell(f)}</td><td>${getStatusBadge(f.status)}</td></tr>`).join('')||'<tr><td colspan="5">ยังไม่มีไฟล์งาน</td></tr>';}
function initEvaluationForm(){const f=document.getElementById('evaluationForm');if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const d={teacherName:v('evalTeacher'),supervisionDate:v('evalDate'),strengths:v('evalStrengths'),improvements:v('evalImprovements'),suggestions:v('evalSuggestions'),summary:v('evalSummary'),timestamp:new Date().toISOString(),id:crypto.randomUUID?crypto.randomUUID():String(Date.now())};const r=await apiPost('addEvaluation',d);if(!r.success)return showToast(r.error||'บันทึกผลประเมินไม่สำเร็จ','error');allEvaluations.push(d);setLocalData('evaluations',allEvaluations);f.reset();showToast('บันทึกผลการประเมินสำเร็จ');loadEvaluationList();});}
function loadEvaluationData(){populateTeacherDropdown('evalTeacher');loadEvaluationList();}
function loadEvaluationList(){const e=document.getElementById('evaluations');if(!e)return;e.innerHTML=allEvaluations.slice(-10).reverse().map(x=>`<tr><td>${formatDate(x.timestamp)}</td><td>${esc(x.teacherName)}</td><td>${formatDate(x.supervisionDate)}</td><td>${esc(x.strengths)}</td><td>${esc(x.improvements)}</td><td>${getLevelBadge(x.summary)}</td></tr>`).join('')||'<tr><td colspan="6">ยังไม่มีผลการประเมิน</td></tr>';}
function populateTeacherDropdown(id){const s=document.getElementById(id);if(!s)return;const teachers=[...new Set(allBookings.map(x=>x.teacherName).filter(Boolean))];s.innerHTML='<option value="">-- เลือกครู --</option>'+teachers.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('');}
function initCalendars(){const c=document.getElementById('bookingCalendar');if(c&&window.FullCalendar){if(calendarInstances.booking)calendarInstances.booking.destroy();calendarInstances.booking=new FullCalendar.Calendar(c,{initialView:'dayGridMonth',locale:'th',headerToolbar:{left:'prev,next today',center:'title',right:'dayGridMonth'},events:allBookings.map(b=>({title:(b.teacherName||'')+' ('+(b.time||'')+')',date:b.date})),dateClick:i=>{const e=document.getElementById('bookDate');if(e)e.value=i.dateStr}});calendarInstances.booking.render();}}
function refreshCalendars(){initCalendars();loadDashboardCalendar();}
function initAdminTabs(){document.querySelectorAll('.tab-btn').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab)?.classList.add('active');}));}
function loadAdminData(){loadAdminBookings();loadAdminFiles();loadAdminEvaluations();loadAdminUsers();populateTeacherDropdown('reportTeacher');}
function loadAdminBookings(){const e=document.getElementById('adminBookings');if(!e)return;e.innerHTML=allBookings.slice().reverse().map((b,i)=>`<tr><td>${formatDate(b.date)}</td><td>${esc(b.time)}</td><td>${esc(b.teacherName)}</td><td>${esc(b.department)}</td><td>${esc(b.subjectName)}</td><td>${esc(b.classLevel)}/${esc(b.room)}</td><td>${getStatusBadge(b.status)}</td><td><button class="btn btn-success btn-sm" onclick="updateBookingStatus(${i},'ยืนยันแล้ว')">✓</button> <button class="btn btn-danger btn-sm" onclick="updateBookingStatus(${i},'ปฏิเสธ')">✕</button> <button class="btn btn-secondary btn-sm" onclick="deleteBookingAdmin(${i})">🗑</button></td></tr>`).join('')||'<tr><td colspan="8">ไม่มีข้อมูล</td></tr>';}
async function updateBookingStatus(i,status){const b=allBookings.slice().reverse()[i];if(!b)return;const r=await apiPost('updateBookingStatus',{id:b.id,status});if(!r.success)return showToast(r.error||'อัปเดตไม่สำเร็จ','error');b.status=status;showToast('อัปเดตสถานะแล้ว');loadAdminBookings();loadDashboard();refreshCalendars();}
async function deleteBookingAdmin(i){if(!confirm('ต้องการลบการจองนี้ใช่หรือไม่?'))return;const b=allBookings.slice().reverse()[i];const r=await apiPost('deleteBooking',{id:b.id});if(!r.success)return showToast(r.error||'ลบไม่สำเร็จ','error');allBookings=allBookings.filter(x=>x.id!==b.id);loadAdminBookings();loadDashboard();}
function loadAdminFiles(){const e=document.getElementById('adminFiles');if(!e)return;e.innerHTML=allFiles.slice().reverse().map((f,i)=>`<tr><td>${formatDate(f.timestamp)}</td><td>${esc(f.teacherName)}</td><td>${esc(f.fileType)}</td><td>${renderFileCell(f)}</td><td>${getStatusBadge(f.status)}</td><td><button class="btn btn-success btn-sm" onclick="updateFileStatus(${i},'ผ่าน')">✓</button> <button class="btn btn-warning btn-sm" onclick="updateFileStatus(${i},'ปรับปรุง')">!</button> <button class="btn btn-secondary btn-sm" onclick="deleteFileAdmin(${i})">🗑</button></td></tr>`).join('')||'<tr><td colspan="6">ไม่มีไฟล์งาน</td></tr>';}
async function updateFileStatus(i,status){const f=allFiles.slice().reverse()[i];const r=await apiPost('updateFileStatus',{id:f.id,status});if(!r.success)return showToast(r.error||'อัปเดตไม่สำเร็จ','error');f.status=status;loadAdminFiles();}
async function deleteFileAdmin(i){if(!confirm('ต้องการลบไฟล์งานนี้ใช่หรือไม่?'))return;const f=allFiles.slice().reverse()[i];const r=await apiPost('deleteFile',{id:f.id});if(!r.success)return showToast(r.error||'ลบไม่สำเร็จ','error');allFiles=allFiles.filter(x=>x.id!==f.id);loadAdminFiles();loadMyFiles();}
function loadAdminEvaluations(){const e=document.getElementById('adminEvaluations');if(!e)return;e.innerHTML=allEvaluations.slice().reverse().map((x,i)=>`<tr><td>${formatDate(x.timestamp)}</td><td>${esc(x.teacherName)}</td><td>${formatDate(x.supervisionDate)}</td><td>${esc(x.strengths)}</td><td>${esc(x.improvements)}</td><td>${esc(x.suggestions)}</td><td>${getLevelBadge(x.summary)}</td><td><button class="btn btn-secondary btn-sm" onclick="deleteEvaluationAdmin(${i})">🗑</button></td></tr>`).join('')||'<tr><td colspan="8">ไม่มีข้อมูล</td></tr>';}
async function deleteEvaluationAdmin(i){if(!confirm('ต้องการลบผลการประเมินนี้ใช่หรือไม่?'))return;const x=allEvaluations.slice().reverse()[i];const r=await apiPost('deleteEvaluation',{id:x.id});if(!r.success)return showToast(r.error||'ลบไม่สำเร็จ','error');allEvaluations=allEvaluations.filter(a=>a.id!==x.id);loadAdminEvaluations();loadEvaluationList();}
async function loadUsersData(){const r=await apiCall('getUsers');allUsers=r.data||[];}
function loadAdminUsers(){const e=document.getElementById('adminUsers');if(!e)return;e.innerHTML=allUsers.map((u,i)=>`<tr><td>${esc(u.username)}</td><td>${esc(u.fullName)}</td><td>${esc(u.department)}</td><td>${esc(u.role)}</td><td>${String(u.active)!=='false'?'ใช้งาน':'ปิด'}</td><td>${u.username==='admin'?'บัญชีหลัก':`<button class="btn btn-secondary btn-sm" onclick="deleteUserAdmin(${i})">ลบ</button>`}</td></tr>`).join('')||'<tr><td colspan="6">ไม่มีผู้ใช้</td></tr>';}
function initReportButtons(){document.getElementById('printIndividualReport')?.addEventListener('click',()=>window.print());document.getElementById('printDeptReport')?.addEventListener('click',()=>window.print());}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}function v(id){return document.getElementById(id)?.value?.trim()||'';}function formatDate(s){if(!s)return'-';const d=new Date(s);return isNaN(d)?String(s):d.toLocaleDateString('th-TH',{year:'numeric',month:'short',day:'numeric'});}function getStatusBadge(s){return `<span class="badge">${esc(s||'-')}</span>`;}function getLevelBadge(s){return `<span class="badge">${esc(s||'-')}</span>`;}
function renderFileCell(f){if(f.fileUrl)return `<a href="${esc(f.fileUrl)}" target="_blank"><i class="fas fa-file"></i> ${esc(f.fileName||'เปิดไฟล์')}</a>`;return esc(f.fileName||'-');}
function readFileAsBase64Legacy(f){return readFileAsBase64(f);}