const SPREADSHEET_ID='1e5530q7hRUdR6pNIx6tAv4JjNKadFibg7GE5ohuq4xU';
const DRIVE_FOLDER_ID='1wVAG7EETgBcv5ftOFLLzdX-wbDEK95Dw';
const APP_NAME='Takbai Internal Supervision API';
const VERSION='2026-08-18-complete-v5';
const SESSION_TTL=21600;
const AREAS=['ภาษาไทย','คณิตศาสตร์','วิทยาศาสตร์และเทคโนโลยี','สังคมศึกษา ศาสนาและวัฒนธรรม','สุขศึกษาและพลศึกษา','ศิลปะ ดนตรี นาฏศิลป์','การงานอาชีพ','ภาษาต่างประเทศ','อื่นๆ'];
const TEACHERS=[
['นางสาว','วัลภา','มะเอียด'],['ว่าที่ ร.อ.','สามารถ','นุธรรมโชติ'],['นางสาว','ซูเลียนา','บือซา'],['นางสาว','นาซีรา','หะยีนอ'],['นาง','ลออ','คงเจริญ'],['นางสาว','นูรุลอัยน์','มีซอ'],['นาย','อภิชาติ','รักเถาว์'],['นาย','จินดา','คงเจริญ'],['นางสาว','มาห์มูด๊ะ','มอลอ'],['นาย','ภูริวัฒน์','อมรชาติ'],['นางสาว','ปราณี','บัวแก้ว'],['นาง','พเยาว์','ประสิทธิชัยวุฒิ'],['นาง','นภาเพ็ญ','ทองจินดา'],['นาง','สาลินี','อารอมะ'],['นางสาว','ฮาฟีดะห์','สะนิบากอ'],['นาง','นภัสลักษณ์','พจน์เพริศ'],['นาย','วัฒนา','จินดาเพ็ชร'],['นาง','นุชนาฏ','เข็มทอง'],['นางสาว','เกณิกา','เมฆเจริญวิวัฒนา'],['นางสาว','จีรวรรณ','ทองชาติ'],['นาง','อรอุมา','แววภักดี'],['นางสาว','ซากีหย๊ะ','เด็งจิ'],['นาย','ธนภัทร์','ปั้นแก้ว'],['นางสาว','กุลธิดา','ศรีดำ'],['นาย','อารีฟิน','มูซอ'],['นางสาว','ซูไมย๊ะ','บูกุ'],['นางสาว','ฮัสมารีซา','ยะโก๊ะ'],['นาย','มูหัมมัด','แวยุนุ'],['นางสาว','สูรียานา','สือนิ'],['นางสาว','พรพิมล','สุขศรีแดง'],['นางสาว','สุลนา','เสาร์พูล'],['นาย','สุวัฒน์','จีนขุ้ย'],['นางสาว','สมฤดี','แดงเตี้ย'],['นาย','แวอิสมาแอ','บินแวอูมา']
];
function doGet(e){try{const p=(e&&e.parameter)||{};return output_(routeGet_(p),p.callback);}catch(err){return output_({success:false,error:err.message||String(err)},(e&&e.parameter||{}).callback);}}
function doPost(e){try{return output_(routePost_(parse_(e)),null);}catch(err){return output_({success:false,error:err.message||String(err)},null);}}
function parse_(e){if(!e)return{};if(e.postData&&e.postData.contents){try{return JSON.parse(e.postData.contents);}catch(_){} }return Object.assign({},e.parameter||{});}
function output_(obj,cb){const json=JSON.stringify(obj||{});if(cb&&/^[A-Za-z_$][0-9A-Za-z_$\.]*$/.test(cb))return ContentService.createTextOutput(cb+'('+json+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(json).setMimeType(ContentService.MimeType.JSON);}
function defs_(){return {Booking:bookingH_(),Files:fileH_(),Supervision:supervisionH_(),Users:userH_(),Teachers:teacherH_(),LearningAreas:areaH_(),AuditLog:auditH_(),SystemConfig:['Key','Value','UpdatedAt']};}
function bookingH_(){return ['Timestamp','Date','Time','Teacher Name','Department','Period','Subject Name','Subject Code','Class Level','Room','Status','ID'];}
function fileH_(){return ['Timestamp','Teacher Name','File Type','File URL/Link','Drive File ID','File Name','Status','SubmittedBy','ReviewedAt','ReviewedBy','ReviewComment','ID'];}
function supervisionH_(){return ['Timestamp','Supervision Type','Supervisor Name','Teacher Name','Subject Group','Grade Level','Period','Teaching Date','Topic','Teaching Techniques','Scores JSON','Total Score','Percent','Quality Level','Strengths','Improvements','Suggestions','Evidence File URL','Evidence Drive File ID','Evidence File Name','Status','ReviewedAt','ReviewedBy','ReviewComment','ID'];}
function userH_(){return ['Username','Password','Role','FullName','Department','Active','ID'];}
function teacherH_(){return ['ID','Prefix','FirstName','LastName','FullName','Active','UpdatedAt'];}
function areaH_(){return ['ID','Name','Active','UpdatedAt'];}
function auditH_(){return ['Timestamp','Username','Action','Entity','EntityID','Details'];}
function setup_(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),d=defs_(),created=[];Object.keys(d).forEach(n=>{const before=ss.getSheetByName(n);ensure_(n,d[n]);if(!before)created.push(n);});seedAdmin_();seedTeachers_();seedAreas_();return {success:true,spreadsheetId:SPREADSHEET_ID,sheets:Object.keys(d),created};}
function ensure_(name,h){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.getRange(1,1,1,h.length).setValues([h]);else if(h.some((x,i)=>String(sh.getRange(1,i+1).getValue()||'')!==x))sh.getRange(1,1,1,h.length).setValues([h]);sh.setFrozenRows(1);return sh;}
function seedAdmin_(){const sh=ensure_('Users',userH_());if(sh.getLastRow()<2)sh.appendRow(['admin','Admin@123','admin','ผู้ดูแลระบบ','-',true,'u_admin']);}
function seedTeachers_(){const sh=ensure_('Teachers',teacherH_());if(sh.getLastRow()>=2)return;TEACHERS.forEach((t,i)=>sh.appendRow(['t_'+String(i+1).padStart(3,'0'),t[0],t[1],t[2],t.join(' '),true,new Date()]));}
function seedAreas_(){const sh=ensure_('LearningAreas',areaH_());if(sh.getLastRow()>=2)return;AREAS.forEach((n,i)=>sh.appendRow(['a_'+String(i+1).padStart(2,'0'),n,true,new Date()]));}
function health_(){const r={success:true,service:APP_NAME,version:VERSION,spreadsheetId:SPREADSHEET_ID,driveFolderId:DRIVE_FOLDER_ID,timestamp:new Date().toISOString()};try{const ss=SpreadsheetApp.openById(SPREADSHEET_ID);r.spreadsheetAccessible=true;r.spreadsheetName=ss.getName();r.sheets=setup_().sheets;}catch(e){r.spreadsheetAccessible=false;r.spreadsheetError=e.message||String(e);}try{r.driveFolderName=DriveApp.getFolderById(DRIVE_FOLDER_ID).getName();r.driveAccessible=true;}catch(e){r.driveAccessible=false;r.driveError=e.message||String(e);}return r;}
function routeGet_(p){switch(String(p.action||'health')){case'health':case'debug':return health_();case'setup':return setup_();case'getBookings':return list_('Booking',bookingH_());case'getFiles':return list_('Files',fileH_());case'getEvaluations':return list_('Supervision',supervisionH_());case'getTeachers':return list_('Teachers',teacherH_());case'getLearningAreas':return list_('LearningAreas',areaH_());case'getUsers':return getUsers_(p.authToken);case'getDashboard':return dashboard_();default:return{success:false,error:'Unknown GET action: '+p.action};}}
function routePost_(d){switch(String(d.action||'')){case'health':return health_();case'setup':return setup_();case'login':return login_(d);case'addBooking':return addBooking_(d);case'updateBookingStatus':{const a=auth_(d.authToken,true);return a.ok?update_('Booking',d.id,{status:d.status}):a.result;}case'updateBooking':return update_('Booking',d.id,d);case'deleteBooking':return del_('Booking',d.id);case'addFile':return addFile_(d);case'uploadFileToDrive':return uploadFile_(d);case'updateFileStatus':return reviewFile_(d);case'deleteFile':{const a=auth_(d.authToken,true);return a.ok?del_('Files',d.id):a.result;}case'addEvaluation':case'saveSupervisionData':return saveSupervision_(d);case'updateEvaluation':return updateSupervision_(d);case'updateSupervisionStatus':return reviewSupervision_(d);case'deleteEvaluation':{const a=auth_(d.authToken,true);return a.ok?del_('Supervision',d.id):a.result;}case'addUser':case'updateUser':case'deleteUser':case'addTeacher':case'updateTeacher':case'deleteTeacher':return adminWrite_(d);default:return{success:false,error:'Unknown POST action: '+d.action};}}
function list_(name,h){const sh=ensure_(name,h),lr=sh.getLastRow();if(lr<2)return{success:true,data:[]};const rows=sh.getRange(2,1,lr-1,h.length).getValues();return{success:true,data:rows.map(r=>obj_(h,r))};}
function obj_(h,r){const map={'Timestamp':'timestamp','Date':'date','Time':'time','Teacher Name':'teacherName','Department':'department','Period':'period','Subject Name':'subjectName','Subject Code':'subjectCode','Class Level':'classLevel','Room':'room','Status':'status','ID':'id','File Type':'fileType','File URL/Link':'fileUrl','Drive File ID':'driveFileId','File Name':'fileName','SubmittedBy':'submittedBy','ReviewedAt':'reviewedAt','ReviewedBy':'reviewedBy','ReviewComment':'reviewComment','Supervision Type':'supervisionType','Supervisor Name':'supervisorName','Subject Group':'subjectGroup','Grade Level':'gradeLevel','Teaching Date':'teachingDate','Topic':'topic','Teaching Techniques':'teachingTechniques','Scores JSON':'scoresJson','Total Score':'totalScore','Percent':'percent','Quality Level':'qualityLevel','Strengths':'strengths','Improvements':'improvements','Suggestions':'suggestions','Evidence File URL':'evidenceFileUrl','Evidence Drive File ID':'evidenceDriveFileId','Evidence File Name':'evidenceFileName','Username':'username','Password':'password','Role':'role','FullName':'fullName','Active':'active','Prefix':'prefix','FirstName':'firstName','LastName':'lastName','UpdatedAt':'updatedAt','Name':'name'};const o={};h.forEach((x,i)=>o[map[x]||x]=r[i] instanceof Date?r[i].toISOString():r[i]);if(o.scoresJson){try{o.scores=JSON.parse(o.scoresJson);}catch(_){o.scores=[];}}return o;}
function id_(){return Utilities.getUuid();}
function addBooking_(d){const id=d.id||id_();ensure_('Booking',bookingH_()).appendRow([new Date(),d.date||'',d.time||'',d.teacherName||'',d.department||'',d.period||'',d.subjectName||'',d.subjectCode||'',d.classLevel||'',d.room||'',d.status||'รอดำเนินการ',id]);audit_(d,'add','Booking',id);return{success:true,id};}
function uploadFile_(d){if(!d.fileData||!d.fileName)return{success:false,error:'ข้อมูลไฟล์ไม่ครบ'};try{const folder=DriveApp.getFolderById(DRIVE_FOLDER_ID),raw=String(d.fileData),bytes=Utilities.base64Decode(raw.replace(/^data:[^;]+;base64,/,'').split(',').pop()),blob=Utilities.newBlob(bytes,d.mimeType||'application/octet-stream',d.fileName),f=folder.createFile(blob);try{f.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);}catch(_){}return{success:true,fileId:f.getId(),fileUrl:'https://drive.google.com/file/d/'+f.getId()+'/view',fileName:f.getName()};}catch(e){return{success:false,error:e.message||String(e)};}}
function addFile_(d){const id=d.id||id_();ensure_('Files',fileH_()).appendRow([new Date(),d.teacherName||'',d.fileType||'',d.fileUrl||'',d.driveFileId||'',d.fileName||'',d.status||'รอตรวจสอบ',d.submittedBy||d.teacherName||'','','','',id]);audit_(d,'add','Files',id);return{success:true,id};}
function saveSupervision_(d){let scores=[];try{scores=Array.isArray(d.scores)?d.scores:(typeof d.scores==='string'?JSON.parse(d.scores||'[]'):[]);}catch(_){scores=[];}if(scores.length!==25||scores.some(x=>x===null||x===undefined||Number(x)<0||Number(x)>4))return{success:false,error:'ต้องประเมินให้ครบทั้ง 25 ข้อ และคะแนนต้องอยู่ระหว่าง 0-4'};const total=scores.reduce((a,b)=>a+Number(b),0),percent=total,level=quality_(percent),id=d.id||id_();let evidence={};if(d.evidenceFile&&d.evidenceFile.dataUrl){const u=uploadFile_({fileData:d.evidenceFile.dataUrl,fileName:d.evidenceFile.name,mimeType:d.evidenceFile.mimeType});if(!u.success)return u;evidence={url:u.fileUrl,id:u.fileId,name:u.fileName};}ensure_('Supervision',supervisionH_()).appendRow([new Date(),d.supervisionType||'',d.supervisorName||'',d.teacherName||'',d.subjectGroup||'',d.gradeLevel||'',d.period||'',d.teachingDate||'',d.topic||'',d.teachingTechniques||'',JSON.stringify(scores),total,percent,level,d.strengths||'',d.improvements||'',d.suggestions||'',evidence.url||'',evidence.id||'',evidence.name||'',d.status||'รอตรวจสอบ','','','',id]);audit_(d,'add','Supervision',id);return{success:true,id,totalScore:total,percent,qualityLevel:level,evidenceFile:evidence};}
function quality_(p){if(p>=90)return'ดีมาก';if(p>=80)return'ดี';if(p>=70)return'พอใช้';if(p>=60)return'ควรปรับปรุง';return'ไม่ผ่านเกณฑ์';}
function login_(d){const u=String(d.username||'').trim(),p=String(d.password||'');if(!u||!p)return{success:false,error:'กรุณากรอกชื่อผู้ใช้และรหัสผ่าน'};const r=list_('Users',userH_()),user=(r.data||[]).find(x=>String(x.username)===u&&String(x.password)===p);if(!user)return{success:false,error:'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง'};if(String(user.active).toLowerCase()==='false')return{success:false,error:'บัญชีนี้ถูกปิดการใช้งาน'};const token=id_()+'-'+id_();CacheService.getScriptCache().put('auth_'+token,JSON.stringify({id:user.id,username:user.username,role:user.role,fullName:user.fullName,department:user.department}),SESSION_TTL);return{success:true,user:{id:user.id,username:user.username,role:user.role,fullName:user.fullName,department:user.department,authToken:token}};}
function auth_(token,admin){if(!token)return{ok:false,result:{success:false,error:'กรุณาเข้าสู่ระบบก่อน'}};const raw=CacheService.getScriptCache().get('auth_'+token);if(!raw)return{ok:false,result:{success:false,error:'เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่'}};const u=JSON.parse(raw);if(admin&&u.role!=='admin')return{ok:false,result:{success:false,error:'ไม่มีสิทธิ์ผู้ดูแลระบบ'}};return{ok:true,user:u};}
function getUsers_(token){const r=list_('Users',userH_()),a=auth_(token,true);if(a.ok)return r;return{success:true,data:(r.data||[]).map(u=>({id:u.id,username:u.username,role:u.role,fullName:u.fullName,department:u.department,active:u.active}))};}
function adminWrite_(d){const a=auth_(d.authToken,true);if(!a.ok)return a.result;switch(d.action){case'addUser':return addUser_(d);case'updateUser':return updateUser_(d);case'deleteUser':return deleteUser_(d);case'addTeacher':return addTeacher_(d);case'updateTeacher':return updateTeacher_(d);case'deleteTeacher':return deleteTeacher_(d);}}
function addUser_(d){const sh=ensure_('Users',userH_()),u=String(d.username||'').trim();if(!u||!d.password)return{success:false,error:'กรุณาระบุชื่อผู้ใช้และรหัสผ่าน'};const rows=list_('Users',userH_()).data;if(rows.some(x=>String(x.username).toLowerCase()===u.toLowerCase()))return{success:false,error:'ชื่อผู้ใช้นี้มีอยู่แล้ว'};const id=d.id||id_();sh.appendRow([u,String(d.password),d.role==='admin'?'admin':'user',d.fullName||'',d.department||'-',d.active!==false,id]);audit_(d,'add','Users',id);return{success:true,id};}
function findRow_(name,id){const sh=ensure_(name,defs_()[name]),lr=sh.getLastRow();if(lr<2)return-1;const vals=sh.getRange(2,sh.getLastColumn(),lr-1,1).getValues();for(let i=0;i<vals.length;i++)if(String(vals[i][0])===String(id))return i+2;return-1;}
function update_(name,id,d){const h=defs_()[name],sh=ensure_(name,h),row=findRow_(name,id);if(row<0)return{success:false,error:'ไม่พบรายการ'};const map={'date':'Date','time':'Time','teacherName':'Teacher Name','department':'Department','period':'Period','subjectName':'Subject Name','subjectCode':'Subject Code','classLevel':'Class Level','room':'Room','status':'Status','fileType':'File Type','fileUrl':'File URL/Link','driveFileId':'Drive File ID','fileName':'File Name'};Object.keys(d).forEach(k=>{if(map[k])sh.getRange(row,h.indexOf(map[k])+1).setValue(d[k]);});audit_(d,'update',name,id);return{success:true,id};}
function reviewFile_(d){const a=auth_(d.authToken,true);if(!a.ok)return a.result;const h=fileH_(),sh=ensure_('Files',h),row=findRow_('Files',d.id);if(row<0)return{success:false,error:'ไม่พบไฟล์'};sh.getRange(row,h.indexOf('Status')+1).setValue(d.status||'รอตรวจสอบ');sh.getRange(row,h.indexOf('ReviewedAt')+1).setValue(new Date());sh.getRange(row,h.indexOf('ReviewedBy')+1).setValue(a.user.fullName||a.user.username);sh.getRange(row,h.indexOf('ReviewComment')+1).setValue(d.comment||'');audit_(d,'review','Files',d.id);return{success:true,id:d.id};}
function updateSupervision_(d){const a=auth_(d.authToken,true);if(!a.ok)return a.result;return updateSupervisionFields_(d);}
function reviewSupervision_(d){const a=auth_(d.authToken,true);if(!a.ok)return a.result;const h=supervisionH_(),sh=ensure_('Supervision',h),row=findRow_('Supervision',d.id);if(row<0)return{success:false,error:'ไม่พบผลการนิเทศ'};sh.getRange(row,h.indexOf('Status')+1).setValue(d.status||'รอตรวจสอบ');sh.getRange(row,h.indexOf('ReviewedAt')+1).setValue(new Date());sh.getRange(row,h.indexOf('ReviewedBy')+1).setValue(a.user.fullName||a.user.username);sh.getRange(row,h.indexOf('ReviewComment')+1).setValue(d.comment||'');audit_(d,'review','Supervision',d.id);return{success:true,id:d.id};}
function updateSupervisionFields_(d){const h=supervisionH_(),sh=ensure_('Supervision',h),row=findRow_('Supervision',d.id);if(row<0)return{success:false,error:'ไม่พบผลการนิเทศ'};['strengths','improvements','suggestions','status'].forEach((k,i)=>{if(d[k]!==undefined)sh.getRange(row,h.indexOf(['Strengths','Improvements','Suggestions','Status'][i])+1).setValue(d[k]);});return{success:true,id:d.id};}
function del_(name,id){const sh=ensure_(name,defs_()[name]),row=findRow_(name,id);if(row<0)return{success:false,error:'ไม่พบรายการ'};sh.deleteRow(row);return{success:true,id};}
function updateUser_(d){const sh=ensure_('Users',userH_()),row=findRow_('Users',d.id);if(row<0)return{success:false,error:'ไม่พบผู้ใช้'};const old=sh.getRange(row,1,1,7).getValues()[0],u=d.username===undefined?old[0]:String(d.username).trim(),p=d.password===undefined||String(d.password)===''?old[1]:String(d.password),role=d.role===undefined?old[2]:(d.role==='admin'?'admin':'user'),full=d.fullName===undefined?old[3]:d.fullName,dep=d.department===undefined?old[4]:d.department,active=d.active===undefined?old[5]:String(d.active).toLowerCase()!=='false';if(!u)return{success:false,error:'ชื่อผู้ใช้ห้ามว่าง'};const rows=list_('Users',userH_()).data||[];if(rows.some(x=>x.id!==d.id&&String(x.username).toLowerCase()===u.toLowerCase()))return{success:false,error:'ชื่อผู้ใช้นี้มีอยู่แล้ว'};if(String(old[2])==='admin'&&role!=='admin'&&rows.filter(x=>x.role==='admin').length<=1)return{success:false,error:'ต้องมีผู้ดูแลระบบอย่างน้อย 1 คน'};sh.getRange(row,1,1,7).setValues([[u,p,role,full,dep,active,d.id]]);audit_(d,'update','Users',d.id);return{success:true,id:d.id};}
function deleteUser_(d){const a=auth_(d.authToken,true);if(!a.ok)return a.result;const sh=ensure_('Users',userH_()),row=findRow_('Users',d.id);if(row<0)return{success:false,error:'ไม่พบผู้ใช้'};const target=sh.getRange(row,1,1,7).getValues()[0];if(String(target[6])===String(a.user.id))return{success:false,error:'ไม่สามารถลบบัญชีที่กำลังใช้งานอยู่'};if(String(target[2])==='admin'&&(list_('Users',userH_()).data||[]).filter(x=>x.role==='admin').length<=1)return{success:false,error:'ต้องมีผู้ดูแลระบบอย่างน้อย 1 คน'};sh.deleteRow(row);audit_(d,'delete','Users',d.id);return{success:true,id:d.id};}
function addTeacher_(d){const sh=ensure_('Teachers',teacherH_()),prefix=String(d.prefix||'').trim(),first=String(d.firstName||'').trim(),last=String(d.lastName||'').trim();if(!prefix||!first||!last)return{success:false,error:'กรุณากรอกคำนำหน้า ชื่อ และนามสกุล'};const full=[prefix,first,last].join(' '),rows=list_('Teachers',teacherH_()).data||[];if(rows.some(x=>String(x.fullName).trim()===full))return{success:false,error:'มีรายชื่อนี้อยู่แล้ว'};const id=d.id||id_();sh.appendRow([id,prefix,first,last,full,d.active===undefined||String(d.active).toLowerCase()!=='false',new Date()]);audit_(d,'add','Teachers',id);return{success:true,id,fullName:full};}
function updateTeacher_(d){const sh=ensure_('Teachers',teacherH_()),row=findRow_('Teachers',d.id);if(row<0)return{success:false,error:'ไม่พบรายชื่อครู'};const old=sh.getRange(row,1,1,7).getValues()[0],prefix=d.prefix===undefined?old[1]:String(d.prefix).trim(),first=d.firstName===undefined?old[2]:String(d.firstName).trim(),last=d.lastName===undefined?old[3]:String(d.lastName).trim(),full=[prefix,first,last].join(' '),active=d.active===undefined?old[5]:String(d.active).toLowerCase()!=='false';if(!prefix||!first||!last)return{success:false,error:'ข้อมูลชื่อไม่ครบ'};const rows=list_('Teachers',teacherH_()).data||[];if(rows.some(x=>x.id!==d.id&&String(x.fullName).trim()===full))return{success:false,error:'มีรายชื่อนี้อยู่แล้ว'};sh.getRange(row,1,1,7).setValues([[d.id,prefix,first,last,full,active,new Date()]]);audit_(d,'update','Teachers',d.id);return{success:true,id:d.id,fullName:full};}
function deleteTeacher_(d){const sh=ensure_('Teachers',teacherH_()),row=findRow_('Teachers',d.id);if(row<0)return{success:false,error:'ไม่พบรายชื่อครู'};sh.deleteRow(row);audit_(d,'delete','Teachers',d.id);return{success:true,id:d.id};}
function dashboard_(){const b=list_('Booking',bookingH_()).data||[],f=list_('Files',fileH_()).data||[],s=list_('Supervision',supervisionH_()).data||[],t=list_('Teachers',teacherH_()).data||[],u=list_('Users',userH_()).data||[];return{success:true,stats:{totalBookings:b.length,completed:b.filter(x=>x.status==='นิเทศแล้ว').length,pending:b.filter(x=>x.status==='รอดำเนินการ').length,confirmed:b.filter(x=>x.status==='ยืนยันแล้ว').length,totalFiles:f.length,pendingFiles:f.filter(x=>x.status==='รอตรวจสอบ').length,totalEvaluations:s.length,pendingEvaluations:s.filter(x=>x.status==='รอตรวจสอบ').length,totalTeachers:t.length,totalUsers:u.length}};}
function audit_(d,action,entity,id){try{const a=d&&d.authToken?auth_(d.authToken,false):null;ensure_('AuditLog',auditH_()).appendRow([new Date(),a&&a.ok?a.user.username:'',action,entity,id,JSON.stringify({id})]);}catch(_){} }
