const SPREADSHEET_ID='1e5530q7hRUdR6pNIx6tAv4JjNKadFibg7GE5ohuq4xU';
const DRIVE_FOLDER_ID='1wVAG7EETgBcv5ftOFLLzdX-wbDEK95Dw';
const VERSION='2026-08-18-complete-v8-supervision';
const AREAS=['ภาษาไทย','คณิตศาสตร์','วิทยาศาสตร์และเทคโนโลยี','สังคมศึกษา ศาสนาและวัฒนธรรม','สุขศึกษาและพลศึกษา','ศิลปะ ดนตรี นาฏศิลป์','การงานอาชีพ','ภาษาต่างประเทศ','อื่นๆ'];
const TEACHERS=[['นางสาว','วัลภา','มะเอียด'],['ว่าที่ ร.อ.','สามารถ','นุธรรมโชติ'],['นางสาว','ซูเลียนา','บือซา'],['นางสาว','นาซีรา','หะยีนอ'],['นาง','ลออ','คงเจริญ'],['นางสาว','นูรุลอัยน์','มีซอ'],['นาย','อภิชาติ','รักเถาว์'],['นาย','จินดา','คงเจริญ'],['นางสาว','มาห์มูด๊ะ','มอลอ'],['นาย','ภูริวัฒน์','อมรชาติ'],['นางสาว','ปราณี','บัวแก้ว'],['นาง','พเยาว์','ประสิทธิชัยวุฒิ'],['นาง','นภาเพ็ญ','ทองจินดา'],['นาง','สาลินี','อารอมะ'],['นางสาว','ฮาฟีดะห์','สะนิบากอ'],['นาง','นภัสลักษณ์','พจน์เพริศ'],['นาย','วัฒนา','จินดาเพ็ชร'],['นาง','นุชนาฏ','เข็มทอง'],['นางสาว','เกณิกา','เมฆเจริญวิวัฒนา'],['นางสาว','จีรวรรณ','ทองชาติ'],['นาง','อรอุมา','แววภักดี'],['นางสาว','ซากีหย๊ะ','เด็งจิ'],['นาย','ธนภัทร์','ปั้นแก้ว'],['นางสาว','กุลธิดา','ศรีดำ'],['นาย','อารีฟิน','มูซอ'],['นางสาว','ซูไมย๊ะ','บูกุ'],['นางสาว','ฮัสมารีซา','ยะโก๊ะ'],['นาย','มูหัมมัด','แวยุนุ'],['นางสาว','สูรียานา','สือนิ'],['นางสาว','พรพิมล','สุขศรีแดง'],['นางสาว','สุลนา','เสาร์พูล'],['นาย','สุวัฒน์','จีนขุ้ย'],['นางสาว','สมฤดี','แดงเตี้ย'],['นาย','แวอิสมาแอ','บินแวอูมา']];
const H={Booking:['Timestamp','Date','Time','Teacher Name','Department','Period','Subject Name','Subject Code','Class Level','Room','Status','ID'],Files:['Timestamp','Teacher Name','File Type','File URL/Link','Drive File ID','File Name','Status','SubmittedBy','ReviewedAt','ReviewedBy','ReviewComment','ID'],Supervision:['Timestamp','Supervision Type','Supervisor Name','Teacher Name','Subject Group','Grade Level','Period','Teaching Date','Topic','Teaching Techniques','Scores JSON','Total Score','Percent','Quality Level','Strengths','Improvements','Suggestions','Evidence File URL','Evidence Drive File ID','Evidence File Name','Status','ReviewedAt','ReviewedBy','ReviewComment','ID'],SupervisionDetails:['Timestamp','Supervision ID','Question No','Category','Item','Score','Teacher Name','Supervisor Name','Teaching Date','Status'],Users:['Username','Password','Role','FullName','Department','Active','ID'],Teachers:['ID','Prefix','FirstName','LastName','FullName','Active','UpdatedAt'],LearningAreas:['ID','Name','Active','UpdatedAt'],AuditLog:['Timestamp','Username','Action','Entity','EntityID','Details'],SystemConfig:['Key','Value','UpdatedAt']};
const CRITERIA=[['ด้านการเตรียมการสอน',['จัดทำแผนการเรียนรู้ครบองค์ประกอบ','จัดเตรียมวัสดุ-อุปกรณ์ สื่อ นวัตกรรม กิจกรรมตามแผนฯ']],['ด้านการจัดกิจกรรมการเรียนรู้',['มีวิธีการนำเข้าสู่บทเรียนที่น่าสนใจ แจ้งวัตถุประสงค์การเรียนรู้','ใช้เทคนิคการสอนที่หลากหลาย เน้นผู้เรียนเป็นสำคัญ','จัดกิจกรรมที่ส่งเสริมให้ค้นคว้าหาคำตอบด้วยตนเอง','จัดกิจกรรมที่ตอบสนองความแตกต่างระหว่างบุคคล','จัดกิจกรรมที่เน้นกระบวนการคิด (วิเคราะห์ สังเคราะห์ สร้างสรรค์)','จัดกิจกรรมให้ผู้เรียนมีส่วนร่วมและแสดงความคิดเห็นเสรี','มีการสอดแทรกคุณธรรม จริยธรรมและคุณลักษณะอันพึงประสงค์','มีการเสริมแรงเมื่อนักเรียนปฏิบัติหรือตอบถูกต้อง','มีการสรุปประเด็น สาระ เนื้อหาในกิจกรรมการเรียนรู้','มอบหมายงานเหมาะสมตามศักยภาพผู้เรียนและเอาใจใส่ดูแล','ใช้เวลาสอนเหมาะสมกับเวลาที่กำหนด']],['ด้านสื่อ นวัตกรรม แหล่งเรียนรู้',['ใช้สื่อที่เหมาะสมกับกิจกรรมและศักยภาพของผู้เรียน','ใช้สื่อ แหล่งการเรียนรู้อย่างหลากหลาย']],['ด้านการวัดและประเมินผล',['สอดคล้องและครอบคลุมจุดประสงค์','ประเมินผลอย่างหลากหลายและครบทั้ง 3 ด้าน (K.P.A.)']],['ด้านสภาพทั่วไป',['การตรงต่อเวลา','การควบคุมความเป็นระเบียบในชั้นเรียน','การจัดบรรยากาศในชั้นเรียน (การจัดห้อง, ความสะอาด)']],['ด้านบุคลิกภาพ',['แต่งกายสุภาพ สะอาดเรียบร้อย เหมาะสมกับกาลเทศะ','ใช้ถ้อยคำสุภาพ ถูกต้อง ระดับเสียงดังชัดเจน','ยิ้มแย้มแจ่มใส และควบคุมอารมณ์ในระหว่างสอนได้ดี','เคลื่อนไหวและแสดงท่าทางในการสอนอย่างมีจุดหมาย','แสดงความรัก ความเมตตา กรุณา เอื้ออาทรต่อศิษย์']]];
function doGet(e){try{const p=e&&e.parameter||{};return out_(routeGet_(p),p.callback);}catch(x){return out_({success:false,error:String(x.message||x)},e&&e.parameter&&e.parameter.callback);}}
function doPost(e){try{return out_(routePost_(parse_(e)),null);}catch(x){return out_({success:false,error:String(x.message||x)},null);}}
function parse_(e){if(e&&e.postData&&e.postData.contents){try{return JSON.parse(e.postData.contents);}catch(_){}}return Object.assign({},e&&e.parameter||{});}
function out_(o,cb){const j=JSON.stringify(o||{});if(cb&&/^[A-Za-z_$][0-9A-Za-z_$\.]*$/.test(cb))return ContentService.createTextOutput(cb+'('+j+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(j).setMimeType(ContentService.MimeType.JSON);}
function setup_(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),created=[];Object.keys(H).forEach(n=>{const old=ss.getSheetByName(n);ensure_(n);if(!old)created.push(n)});seedAdmin_();seedTeachers_();seedAreas_();return{success:true,spreadsheetId:SPREADSHEET_ID,sheets:Object.keys(H),created};}
function ensure_(n){const ss=SpreadsheetApp.openById(SPREADSHEET_ID),sh0=ss.getSheetByName(n),sh=sh0||ss.insertSheet(n),h=H[n];if(sh.getLastRow()===0)sh.getRange(1,1,1,h.length).setValues([h]);else{for(let i=0;i<h.length;i++)if(String(sh.getRange(1,i+1).getValue()||'')!==h[i])sh.getRange(1,i+1).setValue(h[i]);}sh.setFrozenRows(1);return sh;}
function seedAdmin_(){const s=ensure_('Users');if(s.getLastRow()<2)s.appendRow(['admin','Admin@123','admin','ผู้ดูแลระบบ','-',true,'u_admin']);}
function seedTeachers_(){const s=ensure_('Teachers');if(s.getLastRow()>=2)return;TEACHERS.forEach((t,i)=>s.appendRow(['t_'+String(i+1).padStart(3,'0'),t[0],t[1],t[2],t.join(' '),true,new Date()]));}
function seedAreas_(){const s=ensure_('LearningAreas');if(s.getLastRow()>=2)return;AREAS.forEach((n,i)=>s.appendRow(['a_'+String(i+1).padStart(2,'0'),n,true,new Date()]));}
function health_(){const r={success:true,version:VERSION,spreadsheetId:SPREADSHEET_ID,driveFolderId:DRIVE_FOLDER_ID,timestamp:new Date().toISOString()};try{const ss=SpreadsheetApp.openById(SPREADSHEET_ID);r.spreadsheetAccessible=true;r.spreadsheetName=ss.getName();r.sheets=setup_().sheets}catch(e){r.spreadsheetAccessible=false;r.spreadsheetError=String(e.message||e)}try{r.driveFolderName=DriveApp.getFolderById(DRIVE_FOLDER_ID).getName();r.driveAccessible=true}catch(e){r.driveAccessible=false;r.driveError=String(e.message||e)}return r;}
function routeGet_(p){switch(String(p.action||'health')){case'health':case'debug':return health_();case'setup':return setup_();case'getBookings':return list_('Booking');case'getFiles':return list_('Files');case'getEvaluations':return list_('Supervision');case'getTeachers':return list_('Teachers');case'getLearningAreas':return list_('LearningAreas');case'getUsers':return users_(p.authToken);default:return{success:false,error:'Unknown GET action: '+p.action};}}
function routePost_(d){switch(String(d.action||'')){case'health':return health_();case'setup':return setup_();case'login':return login_(d);case'addBooking':return addBooking_(d);case'updateBookingStatus':return adminUpdateBooking_(d);case'deleteBooking':return del_('Booking',d.id);case'addFile':return addFile_(d);case'uploadFileToDrive':return uploadFile_(d);case'uploadEvidence':return uploadEvidence_(d);case'updateFileStatus':return reviewFile_(d);case'deleteFile':return adminDelete_(d,'Files');case'saveSupervisionData':case'addEvaluation':return saveSupervision_(d);case'updateSupervisionStatus':return reviewSupervision_(d);case'deleteEvaluation':return adminDelete_(d,'Supervision');case'addUser':case'updateUser':case'deleteUser':case'addTeacher':case'updateTeacher':case'deleteTeacher':return adminWrite_(d);default:return{success:false,error:'Unknown POST action: '+d.action};}}
function list_(n){const s=ensure_(n),h=H[n],lr=s.getLastRow();if(lr<2)return{success:true,data:[]};const rows=s.getRange(2,1,lr-1,h.length).getValues();return{success:true,data:rows.map(r=>row_(n,r))};}
function row_(n,r){const maps={Booking:['timestamp','date','time','teacherName','department','period','subjectName','subjectCode','classLevel','room','status','id'],Files:['timestamp','teacherName','fileType','fileUrl','driveFileId','fileName','status','submittedBy','reviewedAt','reviewedBy','reviewComment','id'],Supervision:['timestamp','supervisionType','supervisorName','teacherName','subjectGroup','gradeLevel','period','teachingDate','topic','teachingTechniques','scoresJson','totalScore','percent','qualityLevel','strengths','improvements','suggestions','evidenceFileUrl','evidenceDriveFileId','evidenceFileName','status','reviewedAt','reviewedBy','reviewComment','id'],SupervisionDetails:['timestamp','supervisionId','questionNo','category','item','score','teacherName','supervisorName','teachingDate','status'],Users:['username','password','role','fullName','department','active','id'],Teachers:['id','prefix','firstName','lastName','fullName','active','updatedAt'],LearningAreas:['id','name','active','updatedAt'],AuditLog:['timestamp','username','action','entity','entityId','details'],SystemConfig:['key','value','updatedAt']};const o={};(maps[n]||H[n]).forEach((k,i)=>o[k]=r[i] instanceof Date?r[i].toISOString():r[i]);if(o.scoresJson){try{o.scores=JSON.parse(o.scoresJson)}catch(_){o.scores=[]}}return o;}
function id_(){return Utilities.getUuid();}
function addBooking_(d){const id=d.id||id_();ensure_('Booking').appendRow([new Date(),d.date||'',d.time||'',d.teacherName||'',d.department||'',d.period||'',d.subjectName||'',d.subjectCode||'',d.classLevel||'',d.room||'',d.status||'รอดำเนินการ',id]);audit_(d,'add','Booking',id);return{success:true,id};}
function addFile_(d){const id=d.id||id_();ensure_('Files').appendRow([new Date(),d.teacherName||'',d.fileType||'',d.fileUrl||'',d.driveFileId||'',d.fileName||'',d.status||'รอตรวจสอบ',d.submittedBy||d.teacherName||'','','','',id]);audit_(d,'add','Files',id);return{success:true,id};}
function uploadFile_(d){if(!d.fileData||!d.fileName)return{success:false,error:'ข้อมูลไฟล์ไม่ครบ'};try{const folder=DriveApp.getFolderById(DRIVE_FOLDER_ID),b=Utilities.base64Decode(String(d.fileData).replace(/^data:[^;]+;base64,/,'').split(',').pop()),blob=Utilities.newBlob(b,d.mimeType||'application/octet-stream',d.fileName),f=folder.createFile(blob);try{f.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW)}catch(_){}const id=d.id||id_(),url='https://drive.google.com/file/d/'+f.getId()+'/view';ensure_('Files').appendRow([new Date(),d.teacherName||'',d.fileType||'เอกสาร',url,f.getId(),f.getName(),d.status||'รอตรวจสอบ',d.submittedBy||d.teacherName||'','','','',id]);audit_(d,'add','Files',id);return{success:true,id,fileId:f.getId(),fileUrl:url,fileName:f.getName()}}catch(e){return{success:false,error:String(e.message||e)}}}
function uploadEvidence_(d){if(!d.fileData||!d.fileName)return{success:false,error:'ข้อมูลหลักฐานไม่ครบ'};try{const folder=DriveApp.getFolderById(DRIVE_FOLDER_ID),raw=String(d.fileData),b=Utilities.base64Decode(raw.replace(/^data:[^;]+;base64,/,'').split(',').pop()),blob=Utilities.newBlob(b,d.mimeType||'application/octet-stream',d.fileName),f=folder.createFile(blob);try{f.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW)}catch(_){}return{success:true,fileId:f.getId(),fileUrl:'https://drive.google.com/file/d/'+f.getId()+'/view',fileName:f.getName()};}catch(e){return{success:false,error:String(e.message||e)}}}
function saveSupervision_(d){const lock=LockService.getScriptLock();try{lock.waitLock(15000);}catch(e){return{success:false,error:'ระบบกำลังบันทึกข้อมูลอื่นอยู่ กรุณาลองใหม่อีกครั้ง'}}try{let scores=[];try{scores=Array.isArray(d.scores)?d.scores:JSON.parse(d.scores||'[]')}catch(_){scores=[]}if(!Array.isArray(scores)||scores.length!==25||scores.some(x=>x===null||x===undefined||String(x)===''||isNaN(Number(x))||Number(x)<0||Number(x)>4))return{success:false,error:'ต้องประเมินให้ครบทั้ง 25 ข้อ และคะแนนต้องอยู่ระหว่าง 0-4'};const total=scores.reduce((a,b)=>a+Number(b),0),maxScore=25*4,percent=Math.round(total/maxScore*10000)/100,level=total>=90?'ดีมาก':total>=80?'ดี':total>=70?'พอใช้':total>=60?'ควรปรับปรุง':'ไม่ผ่านเกณฑ์',id=d.id||id_();if(findRow_('Supervision',id)>0)return{success:true,id,totalScore:total,percent,qualityLevel:level,duplicate:true};const supervisor=String(d.supervisorName||'').trim(),teacher=String(d.teacherName||'').trim(),group=String(d.subjectGroup||'').trim(),date=String(d.teachingDate||'').trim();if(!supervisor||!teacher||!group||!date)return{success:false,error:'กรุณากรอกข้อมูลผู้นิเทศ ผู้รับการนิเทศ กลุ่มสาระ และวันที่สอนให้ครบ'};let ef=d.evidenceFile||null;if(typeof ef==='string'){try{ef=JSON.parse(ef)}catch(_){ef=null}}let ev={};if(ef&&ef.dataUrl){if(String(ef.dataUrl).length>7*1024*1024)return{success:false,error:'ไฟล์หลักฐานมีขนาดใหญ่เกินไป'};const u=uploadEvidence_({fileData:ef.dataUrl,fileName:ef.name,mimeType:ef.mimeType});if(!u.success)return u;ev={url:u.fileUrl,id:u.fileId,name:u.fileName}}else if(d.evidenceFileUrl){ev={url:d.evidenceFileUrl,id:d.evidenceDriveFileId||'',name:d.evidenceFileName||''}}const status=d.status||'รอตรวจสอบ';ensure_('Supervision').appendRow([new Date(),d.supervisionType||'',supervisor,teacher,group,d.gradeLevel||'',d.period||'',date,d.topic||'',d.teachingTechniques||'',JSON.stringify(scores),total,percent,level,d.strengths||'',d.improvements||'',d.suggestions||'',ev.url||'',ev.id||'',ev.name||'',status,'','','',id]);const detail=ensure_('SupervisionDetails'),now=new Date(),rows=[];let q=0;CRITERIA.forEach(g=>g[1].forEach(item=>{q++;rows.push([now,id,q,g[0],item,Number(scores[q-1]),teacher,supervisor,date,status]);}));detail.getRange(detail.getLastRow()+1,1,rows.length,H.SupervisionDetails.length).setValues(rows);audit_(d,'add','Supervision',id);return{success:true,id,totalScore:total,percent,qualityLevel:level,answeredCount:25,maxScore,evidenceFileUrl:ev.url||'',evidenceDriveFileId:ev.id||'',evidenceFileName:ev.name||''};}catch(e){return{success:false,error:'บันทึกผลการนิเทศไม่สำเร็จ: '+String(e.message||e)};}finally{try{lock.releaseLock()}catch(_){}}}
function login_(d){const u=String(d.username||'').trim(),p=String(d.password||'');if(!u||!p)return{success:false,error:'กรุณากรอกชื่อผู้ใช้และรหัสผ่าน'};const user=(list_('Users').data||[]).find(x=>String(x.username)===u&&String(x.password)===p);if(!user)return{success:false,error:'ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง'};if(String(user.active).toLowerCase()==='false')return{success:false,error:'บัญชีนี้ถูกปิดการใช้งาน'};const token=id_()+'-'+id_();CacheService.getScriptCache().put('auth_'+token,JSON.stringify({id:user.id,username:user.username,role:user.role,fullName:user.fullName,department:user.department}),21600);return{success:true,user:{id:user.id,username:user.username,role:user.role,fullName:user.fullName,department:user.department,authToken:token}};}
function auth_(t,admin){if(!t)return{ok:false,result:{success:false,error:'กรุณาเข้าสู่ระบบก่อน'}};const raw=CacheService.getScriptCache().get('auth_'+t);if(!raw)return{ok:false,result:{success:false,error:'เซสชันหมดอายุ กรุณาเข้าสู่ระบบใหม่'}};const u=JSON.parse(raw);if(admin&&u.role!=='admin')return{ok:false,result:{success:false,error:'ไม่มีสิทธิ์ผู้ดูแลระบบ'}};return{ok:true,user:u};}
function users_(t){const r=list_('Users'),a=auth_(t,true);if(a.ok)return r;return{success:true,data:(r.data||[]).map(x=>({id:x.id,username:x.username,role:x.role,fullName:x.fullName,department:x.department,active:x.active}))};}
function adminUpdateBooking_(d){const a=auth_(d.authToken,true);return a.ok?update_('Booking',d.id,{status:d.status}):a.result;}
function update_(n,id,d){const s=ensure_(n),h=H[n],row=findRow_(n,id);if(row<0)return{success:false,error:'ไม่พบรายการ'};const map={date:'Date',time:'Time',teacherName:'Teacher Name',department:'Department',period:'Period',subjectName:'Subject Name',subjectCode:'Subject Code',classLevel:'Class Level',room:'Room',status:'Status',fileType:'File Type',fileUrl:'File URL/Link',driveFileId:'Drive File ID',fileName:'File Name'};Object.keys(d).forEach(k=>{if(map[k])s.getRange(row,h.indexOf(map[k])+1).setValue(d[k])});return{success:true,id};}
function reviewFile_(d){const a=auth_(d.authToken,true);if(!a.ok)return a.result;const s=ensure_('Files'),h=H.Files,row=findRow_('Files',d.id);if(row<0)return{success:false,error:'ไม่พบไฟล์'};s.getRange(row,h.indexOf('Status')+1).setValue(d.status||'รอตรวจสอบ');s.getRange(row,h.indexOf('ReviewedAt')+1).setValue(new Date());s.getRange(row,h.indexOf('ReviewedBy')+1).setValue(a.user.fullName||a.user.username);s.getRange(row,h.indexOf('ReviewComment')+1).setValue(d.comment||'');return{success:true,id:d.id};}
function reviewSupervision_(d){const a=auth_(d.authToken,true);if(!a.ok)return a.result;const s=ensure_('Supervision'),h=H.Supervision,row=findRow_('Supervision',d.id);if(row<0)return{success:false,error:'ไม่พบผลการนิเทศ'};const status=d.status||'รอตรวจสอบ';s.getRange(row,h.indexOf('Status')+1).setValue(status);s.getRange(row,h.indexOf('ReviewedAt')+1).setValue(new Date());s.getRange(row,h.indexOf('ReviewedBy')+1).setValue(a.user.fullName||a.user.username);s.getRange(row,h.indexOf('ReviewComment')+1).setValue(d.comment||'');const ds=ensure_('SupervisionDetails'),dl=ds.getLastRow();if(dl>=2){const vals=ds.getRange(2,1,dl-1,H.SupervisionDetails.length).getValues();for(let i=0;i<vals.length;i++)if(String(vals[i][1])===String(d.id))ds.getRange(i+2,H.SupervisionDetails.indexOf('Status')+1).setValue(status);}return{success:true,id:d.id};}
function adminDelete_(d,n){const a=auth_(d.authToken,true);return a.ok?del_(n,d.id):a.result;}
function del_(n,id){const s=ensure_(n),row=findRow_(n,id);if(row<0)return{success:false,error:'ไม่พบรายการ'};s.deleteRow(row);if(n==='Supervision'){const ds=ensure_('SupervisionDetails'),lr=ds.getLastRow();if(lr>=2){const vals=ds.getRange(2,1,lr-1,H.SupervisionDetails.length).getValues();for(let i=vals.length-1;i>=0;i--)if(String(vals[i][1])===String(id))ds.deleteRow(i+2);}}return{success:true,id};}
function findRow_(n,id){const s=ensure_(n),lr=s.getLastRow();if(lr<2)return-1;const idCol=H[n].indexOf('ID');if(idCol<0)return-1;const a=s.getRange(2,idCol+1,lr-1,1).getValues();for(let i=0;i<a.length;i++)if(String(a[i][0])===String(id))return i+2;return-1;}
function adminWrite_(d){const a=auth_(d.authToken,true);if(!a.ok)return a.result;if(d.action==='addUser')return addUser_(d);if(d.action==='updateUser')return updateUser_(d);if(d.action==='deleteUser')return deleteUser_(d);if(d.action==='addTeacher')return addTeacher_(d);if(d.action==='updateTeacher')return updateTeacher_(d);return deleteTeacher_(d);}
function addUser_(d){const s=ensure_('Users'),u=String(d.username||'').trim();if(!u||!d.password)return{success:false,error:'กรุณาระบุชื่อผู้ใช้และรหัสผ่าน'};if((list_('Users').data||[]).some(x=>String(x.username).toLowerCase()===u.toLowerCase()))return{success:false,error:'ชื่อผู้ใช้นี้มีอยู่แล้ว'};const id=d.id||id_();s.appendRow([u,String(d.password),d.role==='admin'?'admin':'user',d.fullName||'',d.department||'-',d.active!==false,id]);return{success:true,id};}
function updateUser_(d){const s=ensure_('Users'),row=findRow_('Users',d.id);if(row<0)return{success:false,error:'ไม่พบผู้ใช้'};const old=s.getRange(row,1,1,7).getValues()[0],rows=list_('Users').data||[],u=d.username===undefined?old[0]:String(d.username).trim(),role=d.role===undefined?old[2]:(d.role==='admin'?'admin':'user'),active=d.active===undefined?old[5]:String(d.active).toLowerCase()!=='false';if(rows.some(x=>x.id!==d.id&&String(x.username).toLowerCase()===u.toLowerCase()))return{success:false,error:'ชื่อผู้ใช้นี้มีอยู่แล้ว'};if(String(old[2])==='admin'&&role!=='admin'&&rows.filter(x=>x.role==='admin').length<=1)return{success:false,error:'ต้องมีผู้ดูแลระบบอย่างน้อย 1 คน'};s.getRange(row,1,1,7).setValues([[u,d.password?d.password:old[1],role,d.fullName===undefined?old[3]:d.fullName,d.department===undefined?old[4]:d.department,active,d.id]]);return{success:true,id:d.id};}
function deleteUser_(d){const a=auth_(d.authToken,true);if(!a.ok)return a.result;const s=ensure_('Users'),row=findRow_('Users',d.id);if(row<0)return{success:false,error:'ไม่พบผู้ใช้'};const x=s.getRange(row,1,1,7).getValues()[0];if(String(x[6])===String(a.user.id))return{success:false,error:'ไม่สามารถลบบัญชีที่กำลังใช้งานอยู่'};if(String(x[2])==='admin'&&(list_('Users').data||[]).filter(v=>v.role==='admin').length<=1)return{success:false,error:'ต้องมีผู้ดูแลระบบอย่างน้อย 1 คน'};s.deleteRow(row);return{success:true,id:d.id};}
function addTeacher_(d){const s=ensure_('Teachers'),p=String(d.prefix||'').trim(),f=String(d.firstName||'').trim(),l=String(d.lastName||'').trim(),full=[p,f,l].join(' ');if(!p||!f||!l)return{success:false,error:'กรุณากรอกข้อมูลชื่อให้ครบ'};if((list_('Teachers').data||[]).some(x=>x.fullName===full))return{success:false,error:'มีรายชื่อนี้อยู่แล้ว'};const id=d.id||id_();s.appendRow([id,p,f,l,full,true,new Date()]);return{success:true,id};}
function updateTeacher_(d){const s=ensure_('Teachers'),row=findRow_('Teachers',d.id);if(row<0)return{success:false,error:'ไม่พบรายชื่อครู'};const old=s.getRange(row,1,1,7).getValues()[0],p=d.prefix===undefined?old[1]:d.prefix,f=d.firstName===undefined?old[2]:d.firstName,l=d.lastName===undefined?old[3]:d.lastName,full=[p,f,l].join(' ');s.getRange(row,1,1,7).setValues([[d.id,p,f,l,full,old[5],new Date()]]);return{success:true,id:d.id};}
function deleteTeacher_(d){const s=ensure_('Teachers'),row=findRow_('Teachers',d.id);if(row<0)return{success:false,error:'ไม่พบรายชื่อครู'};s.deleteRow(row);return{success:true,id:d.id};}
function audit_(d,a,e,id){try{const x=d&&d.authToken?auth_(d.authToken,false):null;ensure_('AuditLog').appendRow([new Date(),x&&x.ok?x.user.username:'',a,e,id,JSON.stringify({id})])}catch(_){} }
